### ISSUE TITLE
bbl delete-lbs failed due to a resource dependency on GCP

### ISSUE THREAD

**Issue by JohannaSmith** [cloudfoundry/bosh-bootloader#152] opened 2017-06-09 20:45 UTC
We tried to delete a concourse lb and got the following error
```
bbl --debug delete-lbs
step: generating cloud config
step: applying cloud config
step: generating terraform template
google_compute_target_pool.target-pool: Refreshing state... (ID: bbl-env-nipigon-2017-06-07t21-01z-concourse)
google_compute_network.bbl-network: Refreshing state... (ID: bbl-env-nipigon-2017-06-07t21-01z-network)
google_compute_address.bosh-external-ip: Refreshing state... (ID: bbl-env-nipigon-2017-06-07t21-01z-bosh-external-ip)
google_compute_firewall.internal: Refreshing state... (ID: bbl-env-nipigon-2017-06-07t21-01z-internal)
google_compute_subnetwork.bbl-subnet: Refreshing state... (ID: us-west1/bbl-env-nipigon-2017-06-07t21-01z-subnet)
google_compute_firewall.bosh-open: Refreshing state... (ID: bbl-env-nipigon-2017-06-07t21-01z-bosh-open)
google_compute_target_pool.target-pool: Destroying... (ID: bbl-env-nipigon-2017-06-07t21-01z-concourse)
Error applying plan:

1 error(s) occurred:

* google_compute_target_pool.target-pool (destroy): 1 error(s) occurred:

* google_compute_target_pool.target-pool: Error deleting TargetPool: googleapi: Error 400: The target_pool resource 'projects/cf-core-services/regions/us-west1/targetPools/bbl-env-nipigon-2017-06-07t21-01z-concourse' is already being used by 'projects/cf-core-services/regions/us-west1/forwardingRules/bbl-env-nipigon-2017-06-07t21-forwarding-rule', resourceInUseByAnotherResource

Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.


exit status 1
```

We verified that there were no instances deployed using the bosh director, as well as no other vms in that network. After we manually deleted the `forwarding-rule`, everything worked. There may be a dependency order mismatch in the terraform template which caused `delete-lbs` to fail.

This was on GCP with bbl version `3.2.3` and terraform version `0.9.6`.

cc @zankich

**Comment by genevievelesperance** [comment] 2017-06-09 23:26
@JohannaSmith Did you also bbl up this environment with `3.2.3` or only delete-lbs with the latest?

**Comment by zankich** [comment] 2017-06-09 23:33
This was created and destroyed with 3.2.3.

**Comment by genevievelesperance** [comment] 2017-06-09 23:55
Okay, I'll try to reproduce this because we haven't seen this in our pipelines since these fixes:
https://github.com/cloudfoundry/bosh-bootloader/commit/9f5b6f7de635bc44a6e97d11735e79bfac547805
https://github.com/hashicorp/terraform/pull/14807

**Comment by genevievelesperance** [comment] 2017-06-10 03:30
The problem is terraform version `0.9.6`.
If you bump to `0.9.7` or `0.9.8` the fix for this bug will be in there.
https://github.com/hashicorp/terraform/commit/e9aaf580987859e96511bc0874235d99e234661e

**Closed** 2017-06-10 03:30 UTC
Labels: in progress

**Comment by genevievelesperance** [comment] 2017-06-12 20:40
@zankich @JohannaSmith Let me know if tf 0.9.7+ fixes this for you.
