### ISSUE TITLE
bbl ssh --director is failing

### ISSUE THREAD

**Issue by tariqsiddiqui** [cloudfoundry/bosh-bootloader#339] opened 2018-07-06 14:49 UTC
I am trying to ssh to the bosh director created using bbl and it is failing. I can ssh to the jumpbox without any problem. 

We are running it on AWS. Here is the error message:

[ec2-user@ip-172-31-28-230 bbl_aws]$ bbl ssh --director --debug
Unauthorized use is strictly prohibited. All access and activity
is subject to logging and monitoring.
Ncat: Connection timed out.
ssh_exchange_identification: Connection closed by remote host

exit status 255
[ec2-user@ip-172-31-28-230 bbl_aws]$ bbl -v
bbl 6.6.4 (linux/amd64)
[ec2-user@ip-172-31-28-230 bbl_aws]$

**Comment by joshzarrabi** [comment] 2018-07-12 19:09
It looks like this was a known issue before `bbl` version 6.7. You should upgrade to the latest version of the cli if you can.

**Comment by tariqsiddiqui** [comment] 2018-07-12 19:39
I did and this is what I see:

temp/bbl ssh --director
checking host key
running:
ssh -T jumpbox@52.205.162.216 -i /tmp/174124462/jumpbox-private-key echo host key confirmed
Unauthorized use is strictly prohibited. All access and activity
is subject to logging and monitoring.
host key confirmed
opening a tunnel through your jumpbox
starting:
ssh -4 -D 44689 -nNC jumpbox@52.205.162.216 -i /tmp/174124462/jumpbox-private-key
Unauthorized use is strictly prohibited. All access and activity
is subject to logging and monitoring.
running:
ssh -tt -o StrictHostKeyChecking=no -o ServerAliveInterval=300 -o ProxyCommand=nc -x localhost:44689 %h %p -i /tmp/174124462/director-private-key jumpbox@172.16.0.6
Ncat: Connection timed out.
ssh_exchange_identification: Connection closed by remote host


exit status 255
Killed by signal 2.

**Comment by cwlbraa** [comment] 2018-07-19 19:58
what netcat do you have? Is it the bsd one that supports the `-x` option?

**Comment by cwlbraa** [comment] 2018-07-24 18:43
I'm going to close this. I'm pretty sure this is the netcat thing.

**Closed by cwlbraa** 2018-07-24 18:43 UTC
Labels: unscheduled

**Comment by SergeyMuha** [comment] 2018-09-21 12:43
██bbl ssh --director
checking host key
running:
ssh -T jumpbox@52.11.163.154 -i /tmp/396243710/jumpbox-private-key echo host key confirmed
Unauthorized use is strictly prohibited. All access and activity
is subject to logging and monitoring.
host key confirmed
opening a tunnel through your jumpbox
starting:
ssh -4 -D 41389 -nNC jumpbox@52.11.163.154 -i /tmp/396243710/jumpbox-private-key
Unauthorized use is strictly prohibited. All access and activity
is subject to logging and monitoring.
running:
ssh -tt -o StrictHostKeyChecking=no -o ServerAliveInterval=300 -o ProxyCommand=nc -x localhost:41389 %h %p -i /tmp/396243710/director-private-key jumpbox@10.0.0.6
Ncat: Connection timed out.
ssh_exchange_identification: Connection closed by remote host


exit status 255
Killed by signal 2.

**Comment by wildloop** [comment] 2019-09-02 15:31
There is a difference between `Nmap Ncat` and `OpenBSD netcat`:
- nmap:
```
nc -h
Ncat 7.50 ( https://nmap.org/ncat )
Usage: ncat [options] [hostname] [port]
...
-x, --hex-dump <filename>  Dump session data as hex to a file
```
- openbsd:
```
nc -h
OpenBSD netcat (Debian patchlevel 1.105-7ubuntu1)
...
-x addr[:port]  Specify proxy address and port
```
BBL generated command works only if there is `openbsd-netcat` or `connect-proxy` installed on machine where bbl is executed: https://github.com/cloudfoundry/bosh-bootloader/blob/master/commands/ssh.go#L158
```
proxyCommandPrefix := "nc -x"
if s.pathFinder.CommandExists("connect-proxy") {
	proxyCommandPrefix = "connect-proxy -S"
}
```

To get BBL implementation working in both cases the `connect-proxy` should be required:
```
proxyCommandPrefix := "connect-proxy -S"
if !s.pathFinder.CommandExists("connect-proxy") {
	return fmt.Errorf("Please install connect-proxy")
}
```
or netcat version should be validated, `nc -h` should display this string: `-x addr[:port]`.
