### ISSUE TITLE
`bbl cloud-config` gives error '"" cannot parse CIDR block'

### ISSUE THREAD

**Issue by Amit-PivotalLabs** [cloudfoundry/bosh-bootloader#155] opened 2017-07-02 17:06 UTC
I've `bbl up`d on AWS all the way (without any `--no-director`, etc.).  I've modified my director's Cloud Config, but would like to see what `bbl`'s original Cloud Config looked like.  I saw there's a `bbl cloud-config` command, but when I run it, I get this:

```
$ jq .iaas bbl-state.json
"aws"

$ bbl --version
bbl 3.2.4 (darwin/amd64)

$ bbl --debug cloud-config


"" cannot parse CIDR block
```

**Comment by genevievelesperance** [comment] 2017-10-07 02:13
Hey, since we have not been able to reproduce this issue on that version or later versions of bbl, we'll close this out until we can!

**Closed by genevievelesperance** 2017-10-07 02:13 UTC
Labels: unscheduled
